
schema:
  name: chapter

tree:

  # Defaults style for Graphviz graphs and subgraphs
  graph_defaults:
    all:
      dot:
        ratio: compress
        pad: .5, .5
        ranksep: .3
        concentrate: false

  # Default style for Graphviz nodes
  node_defaults:
    all:
      dot:
        style: filled
        shape: box
        penwidth: 2
        width: 2
        height: .45
        fontname: dejavu sans
    member:
      dot:
        fillcolor: .11 .71 1. # A goldish color
    rank:
      dot:
        color: none
        fontsize: 20
        fontname: georgia
    unknown:
      dot:
        height: 0
        width: 0
        style: invis

  # Default style for Graphviz edges
  edge_defaults:
    all:
      dot:
        arrowhead: none
    rank:
      dot:
        style: invis
    unknown:
      dot:
        style: dotted

  layout:
    ranks: True
    custom_nodes: True
    custom_edges: True
    no_singletons: False
    family_colors: False
    unknowns: True

  # Random seed for ordering family placement
  seed: 54

