
###############################################################################
###############################################################################
#### DATA SOURCES                                                          ####
###############################################################################
###############################################################################

# Uncomment to use a DOT file (formatted similarly to Theta Chi or Delta Chi's
# tree as the data source)
# dot:
#   members: 'tree.dot'

# # Use CSV files as the data source for brothers and big-little pairs
# csv:
#   members: 'directory.csv'
#   affiliations: 'affiliations.csv'

# Use the website's CiviCRM database as the data source
mysql:
  host: '***REMOVED***'
  port: '***REMOVED***'
  user: '***REMOVED***'
  passwd: '***REMOVED***'
  db: '***REMOVED***'

# Tunneling information, if this is not actually running on the server
ssh:
  host: '***REMOVED***'
  port: '***REMOVED***'
  user: '***REMOVED***'
  public_key: '***REMOVED***'

# Use this CSV as the source for additional members. In our case, these are
# brothers who were never made knights since, in the old ritual, you could be a
# "brother" but not have a badge number and not be a knight.
extra_members: 'brothers_not_knights.csv'

###############################################################################
###############################################################################
#### OUTPUT                                                                ####
###############################################################################
###############################################################################

# The output folder and PDF file name
output:
  folder: '.'
  name: 'tree'

