
graphviz:

  # Defaults style for Graphviz graphs and subgraphs
  graph_defaults:
    all:
      size: 80
      ratio: compress
      pad: .5, .5
      ranksep: .3

  # Default style for Graphviz nodes
  node_defaults:
    all:
      style: filled
      shape: box
      penwidth: 2
      width: 2
      height: .45
      fontname: dejavu sans
    member:
      fillcolor: .11 .71 1. # A goldish color
    semester:
      color: none
      fontsize: 20
      fontname: georgia

  # Default style for Graphviz edges
  edge_defaults:
    all:
      arrowhead: none
    semester:
      style: invis

  # Colors for specific families; each badge is the badge of family's head
  family_colors:
    663: deeppink
    760: brown1
    722: red4
    726: lightsteelblue
    673: midnightblue
    716: purple
    702: indianred4
    735: limegreen
    757: darkgreen
    740: royalblue4
    986: yellow
    1043: slategrey
    1044: orangered4
    1045: crimson
    1046: chartreuse4
    1047: cyan2
    1048: sienna2
    1049: salmon2
    1050: cadetblue
    1051: dodgerblue

