
###############################################################################
###############################################################################
#### DATA SOURCES                                                          ####
###############################################################################
###############################################################################

# Use the website's CiviCRM database as the data source
mysql:
  host: '***REMOVED***'
  port: '***REMOVED***'
  user: '***REMOVED***'
  passwd: '***REMOVED***'
  db: '***REMOVED***'

# Credentials for tunneling MySQL queries through SSH
ssh:
  host: '***REMOVED***'
  port: '***REMOVED***'
  user: '***REMOVED***'
  public_key: '***REMOVED***'

